server {
  listen 80;
  server_name _;

  gzip on;
  gzip_types text/plain text/css application/javascript application/json application/xml image/svg+xml;
  error_page 404 /404;

  root /usr/share/nginx/html;
  index index.html;

  location = /robots.txt {
    proxy_pass http://api:8080/robots.txt;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location = /sitemap.xml {
    proxy_pass http://api:8080/sitemap.xml;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /api/ {
    proxy_pass http://api:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location = / {
    try_files /index.html =404;
  }

  location = /404 {
    try_files /index.html =404;
  }

  location = /control-panel {
    try_files /index.html =404;
  }

  location /dashboard {
    try_files /index.html =404;
  }

  location / {
    try_files $uri =404;
  }
}
